ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS account_type text,
  ADD COLUMN IF NOT EXISTS onboarding_completed boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS academic_qualifications text,
  ADD COLUMN IF NOT EXISTS years_of_experience text,
  ADD COLUMN IF NOT EXISTS rate_per_engagement text,
  ADD COLUMN IF NOT EXISTS organisation_type text,
  ADD COLUMN IF NOT EXISTS organisation_website text,
  ADD COLUMN IF NOT EXISTS organisation_size text,
  ADD COLUMN IF NOT EXISTS primary_services_needed text[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS primary_contact_name text,
  ADD COLUMN IF NOT EXISTS advisory_services_needed text,
  ADD COLUMN IF NOT EXISTS country_of_qualification text,
  ADD COLUMN IF NOT EXISTS target_country text,
  ADD COLUMN IF NOT EXISTS orcid_id text,
  ADD COLUMN IF NOT EXISTS google_scholar_url text,
  ADD COLUMN IF NOT EXISTS linkedin_url text,
  ADD COLUMN IF NOT EXISTS wants_peer_review boolean,
  ADD COLUMN IF NOT EXISTS wants_publishing boolean,
  ADD COLUMN IF NOT EXISTS wants_academic_network boolean;